
[package]
name = "turbo-pipeline"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"


[dependencies]
sqlite-vec={version="0.0.1-alpha.7"}
rusqlite = {version="0.31.0", features=["bundled"]}
zerocopy = "0.7.33"
